// Auto-generated by scripts/build-opencode-plugin.sh — do not hand-edit
// agent-notes OpenCode plugin v2.10.0
// AI agent configuration manager for Claude Code, OpenCode, and Copilot
//
// This plugin runs a SessionStart hook that surfaces agent-notes context
// to OpenCode. The full agent/skill team is installed via the Python CLI:
//   pip install agent-notes && agent-notes install

export const AgentNotes = async ({ project, client, $, directory, worktree }) => {
  return {
    "session.start": async () => {
      const vault = "disabled";
      if (vault === "disabled") return;
      try {
        // Surface the agent-notes Index.md if the vault exists
        await $`cat ${vault}/Index.md`.nothrow();
      } catch (err) {
        client.app.log({ level: "debug", message: `agent-notes: vault not readable (${err.message})` });
      }
    }
  };
};
