"""Shared configuration, paths, and utilities."""

import os
import sys
from pathlib import Path
from typing import Optional

# Import UI from services for re-export
from .services.ui import Color, ok, warn, fail, error, info, issue, linked, removed, skipped

# --- Package paths ---
PKG_DIR = Path(__file__).resolve().parent
VERSION_FILE = PKG_DIR / "VERSION"

# Data paths
DATA_DIR = PKG_DIR / "data"
AGENTS_YAML = DATA_DIR / "agents" / "agents.yaml"
AGENTS_DIR = DATA_DIR / "agents"
RULES_DIR = DATA_DIR / "rules"
SKILLS_DIR = DATA_DIR / "skills"
SCRIPTS_DIR = DATA_DIR / "scripts"
MODELS_DIR = DATA_DIR / "models"
ROLES_DIR = DATA_DIR / "roles"

# Dist paths (generated by build)
DIST_DIR = PKG_DIR / "dist"
DIST_RULES_DIR = DIST_DIR / "rules"
DIST_SKILLS_DIR = DIST_DIR / "skills"
DIST_SCRIPTS_DIR = DIST_DIR / "scripts"

# Keep ROOT as alias for compatibility
ROOT = PKG_DIR

# Install target paths (global)
BIN_HOME = Path.home() / ".local" / "bin"
AGENTS_HOME = Path.home() / ".agents"

# Memory (claude-specific legacy)
MEMORY_DIR = Path.home() / ".claude" / "agent-memory"  # Keep claude-specific for backward compatibility
BACKUP_DIR = Path.home() / ".agent-notes" / "memory-backup"


def memory_dir_for_backend(backend: str, custom_path: str = "") -> Optional[Path]:
    """Return the root memory directory for the given backend and optional custom path."""
    if backend == "none":
        return None
    if custom_path:
        return Path(custom_path).expanduser()
    if backend == "obsidian":
        return Path.home() / "agent-memory"
    return MEMORY_DIR  # local default: ~/.claude/agent-memory

def get_version() -> str:
    """Read version from VERSION file."""
    try:
        return VERSION_FILE.read_text().strip()
    except FileNotFoundError:
        return "unknown"

def find_skill_dirs() -> list[Path]:
    """Find all skill directories (containing SKILL.md).
    
    DEPRECATED: Use agent_notes.registries.default_skill_registry() instead.
    This is kept as a shim for backward compatibility.
    """
    # For backward compatibility, first try the original filesystem-based implementation
    # This ensures tests that mock SKILLS_DIR still work
    if SKILLS_DIR.is_dir():
        return sorted(d for d in SKILLS_DIR.iterdir() if d.is_dir() and (d / "SKILL.md").exists())
    return []


# === Registry-driven path helpers ===

def dist_dir_for(backend) -> Path:
    """Return dist directory path for a backend."""
    return DIST_DIR / backend.name


def global_template_path(backend) -> Optional[Path]:
    """Return path to global template source file for backend, or None if no template."""
    if not backend.global_template:
        return None
    return DATA_DIR / backend.global_template


def global_output_path(backend) -> Optional[Path]:
    """Return path where global template should be generated in dist, or None if no template."""
    if not backend.global_template or not backend.layout.get("config"):
        return None
    return dist_dir_for(backend) / backend.layout["config"]


# === Backward compatibility - lazy evaluation of old constants ===
def _lazy_backend_attr(backend_name: str, attr_func):
    """Helper for creating lazy attributes that depend on registry.

    Note: at initial config-module import time, ``agent_notes.cli_backend`` is
    NOT safe to import (circular). In that case we fall back to hardcoded
    values that match the shipped YAMLs. Later callers who import these
    constants after initial module load get the correct values via this same
    function (the registry is then importable).
    """
    def get_attr():
        try:
            from .registries.cli_registry import default_registry
            backend = default_registry().get(backend_name)
            return attr_func(backend)
        except (ImportError, KeyError):
            # Fallback to hardcoded values if registry not available (e.g. circular
            # import at initial module-load time). These match the shipped YAMLs.
            fallbacks = {
                'claude': {'home': Path.home() / ".claude", 'template': "global-claude.md", 'dist': "claude"},
                'opencode': {'home': Path.home() / ".config" / "opencode", 'template': "global-opencode.md", 'dist': "opencode"},
                'copilot': {'home': Path.home() / ".github", 'template': "global-copilot.md", 'dist': "github"},
            }
            fb = fallbacks.get(backend_name, {})
            # Match by the attr_func's role — we encode intent via __name__ for named
            # functions, or by returning the generic dist/home/template via the lambdas
            # below (see DIST_*/GLOBAL_*/*_HOME assignments).
            name = attr_func.__name__
            if name == 'global_home' or name == '_fb_home':
                return fb.get('home')
            elif name == 'template_path' or name == '_fb_template':
                return DATA_DIR / fb.get('template', '')
            elif name == 'dist_dir' or name == '_fb_dist':
                return DIST_DIR / fb.get('dist', backend_name)
    return get_attr


# Create backward-compatibility constants. We give the lambdas named stand-ins
# so the fallback branch in _lazy_backend_attr can classify them correctly even
# when the registry isn't importable yet (circular import during config init).
def _fb_home(b):    return b.global_home
def _fb_dist(b):    return dist_dir_for(b)
def _fb_template(b): return global_template_path(b)

CLAUDE_HOME       = _lazy_backend_attr('claude',   _fb_home)()
OPENCODE_HOME     = _lazy_backend_attr('opencode', _fb_home)()
GITHUB_HOME       = _lazy_backend_attr('copilot',  _fb_home)()
DIST_CLAUDE_DIR   = _lazy_backend_attr('claude',   _fb_dist)()
DIST_OPENCODE_DIR = _lazy_backend_attr('opencode', _fb_dist)()
DIST_GITHUB_DIR   = _lazy_backend_attr('copilot',  _fb_dist)()
GLOBAL_CLAUDE_MD  = _lazy_backend_attr('claude',   _fb_template)()
GLOBAL_OPENCODE_MD = _lazy_backend_attr('opencode', _fb_template)()
GLOBAL_COPILOT_MD = _lazy_backend_attr('copilot',  _fb_template)()