"""Shared configuration, paths, and utilities."""

import os
import sys
from pathlib import Path

# --- Package paths ---
PKG_DIR = Path(__file__).resolve().parent
VERSION_FILE = PKG_DIR / "VERSION"

# Data paths
DATA_DIR = PKG_DIR / "data"
AGENTS_YAML = DATA_DIR / "agents" / "agents.yaml"
AGENTS_DIR = DATA_DIR / "agents"
GLOBAL_MD = DATA_DIR / "global.md"
GLOBAL_COPILOT_MD = DATA_DIR / "global-copilot.md"
RULES_DIR = DATA_DIR / "rules"
SKILLS_DIR = DATA_DIR / "skills"

# Dist paths (generated by build)
DIST_DIR = PKG_DIR / "dist"
DIST_CLAUDE_DIR = DIST_DIR / "claude"
DIST_OPENCODE_DIR = DIST_DIR / "opencode"
DIST_GITHUB_DIR = DIST_DIR / "github"
DIST_RULES_DIR = DIST_DIR / "rules"
DIST_SKILLS_DIR = DIST_DIR / "skills"

# Keep ROOT as alias for compatibility
ROOT = PKG_DIR

# Install target paths (global)
CLAUDE_HOME = Path.home() / ".claude"
OPENCODE_HOME = Path.home() / ".config" / "opencode"
GITHUB_HOME = Path.home() / ".github"
AGENTS_HOME = Path.home() / ".agents"

# Memory
MEMORY_DIR = CLAUDE_HOME / "agent-memory"
BACKUP_DIR = Path.home() / ".agent-notes" / "memory-backup"

# --- Colors ---
class Color:
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    YELLOW = "\033[0;33m"
    CYAN = "\033[0;36m"
    DIM = "\033[2m"
    NC = "\033[0m"  # No color

    @staticmethod
    def disable():
        """Disable colors (for non-TTY output)."""
        for attr in ("RED", "GREEN", "YELLOW", "CYAN", "DIM", "NC"):
            setattr(Color, attr, "")

# Disable colors if not a TTY
if not sys.stdout.isatty():
    Color.disable()

# --- Output helpers ---
def ok(msg: str, indent: int = 2) -> None:
    print(f"{' ' * indent}{Color.GREEN}OK{Color.NC}   {msg}")

def warn(msg: str, indent: int = 2) -> None:
    print(f"{' ' * indent}{Color.YELLOW}WARN{Color.NC} {msg}")

def fail(msg: str, indent: int = 2) -> None:
    print(f"{' ' * indent}{Color.RED}FAIL{Color.NC} {msg}")

def error(msg: str) -> None:
    print(f"{Color.RED}Error: {msg}{Color.NC}", file=sys.stderr)
    sys.exit(1)

def info(msg: str) -> None:
    print(f"  {Color.GREEN}✓{Color.NC} {msg}")

def issue(msg: str) -> None:
    print(f"  {Color.RED}✗{Color.NC} {msg}")

def linked(path: str) -> None:
    print(f"  {Color.GREEN}LINKED{Color.NC}  {path}")

def removed(path: str) -> None:
    print(f"  {Color.GREEN}REMOVED{Color.NC}  {path}")

def skipped(path: str, reason: str = "not a symlink — remove manually") -> None:
    print(f"  {Color.YELLOW}SKIP{Color.NC}     {path} ({reason})")

def get_version() -> str:
    """Read version from VERSION file."""
    try:
        return VERSION_FILE.read_text().strip()
    except FileNotFoundError:
        return "unknown"

def find_skill_dirs() -> list[Path]:
    """Find all skill directories (containing SKILL.md)."""
    if SKILLS_DIR.is_dir():
        return sorted(d for d in SKILLS_DIR.iterdir() if d.is_dir() and (d / "SKILL.md").exists())
    return []