"""Shared configuration, paths, and utilities."""

import os
import sys
from pathlib import Path
from typing import Optional

# Import UI from services for re-export
from .services.ui import Color, ok, warn, fail, error, info, issue, linked, removed, skipped

# --- Package paths ---
PKG_DIR = Path(__file__).resolve().parent
VERSION_FILE = PKG_DIR / "VERSION"

# Data paths
DATA_DIR = PKG_DIR / "data"
AGENTS_YAML = DATA_DIR / "agents" / "agents.yaml"
AGENTS_DIR = DATA_DIR / "agents"
RULES_DIR = DATA_DIR / "rules"
SKILLS_DIR = DATA_DIR / "skills"
MODELS_DIR = DATA_DIR / "models"
ROLES_DIR = DATA_DIR / "roles"

# Dist paths (generated by build)
DIST_DIR = PKG_DIR / "dist"
DIST_RULES_DIR = DIST_DIR / "rules"
DIST_SKILLS_DIR = DIST_DIR / "skills"

# Keep ROOT as alias for compatibility
ROOT = PKG_DIR

# Install target paths (global)
BIN_HOME = Path.home() / ".local" / "bin"
AGENTS_HOME = Path.home() / ".agents"

# Memory (claude-specific legacy)
MEMORY_DIR = Path.home() / ".claude" / "agent-memory"  # Keep claude-specific for backward compatibility
BACKUP_DIR = Path.home() / ".agent-notes" / "memory-backup"


def memory_dir_for_backend(backend: str, custom_path: str = "") -> Optional[Path]:
    """Return the root memory directory for the given backend and optional custom path."""
    if backend == "none":
        return None
    if backend == "local":
        return Path(custom_path).expanduser() if custom_path else MEMORY_DIR
    if backend == "wiki":
        if custom_path:
            return Path(custom_path).expanduser()
        return Path.home() / "Obsidian" / "agent-notes" / "knowledge"
    # obsidian is project-scoped
    if custom_path:
        root = Path(custom_path).expanduser()
    elif backend == "obsidian":
        root = Path.home() / "Obsidian" / "agent-notes" / "notes"
    else:
        return MEMORY_DIR
    project = Path.cwd().name
    return root / project

def get_version() -> str:
    """Read version from VERSION file."""
    try:
        return VERSION_FILE.read_text().strip()
    except FileNotFoundError:
        return "unknown"

def find_skill_dirs() -> list[Path]:
    """Find all skill directories (containing SKILL.md).
    
    DEPRECATED: Use agent_notes.registries.default_skill_registry() instead.
    This is kept as a shim for backward compatibility.
    """
    # For backward compatibility, first try the original filesystem-based implementation
    # This ensures tests that mock SKILLS_DIR still work
    if SKILLS_DIR.is_dir():
        return sorted(d for d in SKILLS_DIR.iterdir() if d.is_dir() and (d / "SKILL.md").exists())
    return []


# === Registry-driven path helpers ===

def dist_dir_for(backend) -> Path:
    """Return dist directory path for a backend."""
    return DIST_DIR / backend.name


def global_template_path(backend) -> Optional[Path]:
    """Return path to global template source file for backend, or None if no template."""
    if not backend.global_template:
        return None
    return DATA_DIR / backend.global_template


def global_output_path(backend) -> Optional[Path]:
    """Return path where global template should be generated in dist, or None if no template."""
    if not backend.global_template or not backend.layout.get("config"):
        return None
    return dist_dir_for(backend) / backend.layout["config"]


# === Backward compatibility constants ===
# Hardcoded fallbacks match the shipped YAMLs and protect against circular
# imports if this module is ever imported very early in the load sequence.
_FALLBACKS = {
    'claude':   {'home': Path.home() / ".claude",               'template': "global-claude.md",   'dist': "claude"},
    'opencode': {'home': Path.home() / ".config" / "opencode",  'template': "global-opencode.md", 'dist': "opencode"},
    'copilot':  {'home': Path.home() / ".github",               'template': "global-copilot.md",  'dist': "github"},
}


def _backend_home(name: str) -> Path:
    try:
        from .registries.cli_registry import default_registry
        return default_registry().get(name).global_home
    except (ImportError, KeyError):
        return _FALLBACKS[name]['home']


def _backend_dist(name: str) -> Path:
    try:
        from .registries.cli_registry import default_registry
        return dist_dir_for(default_registry().get(name))
    except (ImportError, KeyError):
        return DIST_DIR / _FALLBACKS[name]['dist']


def _backend_template(name: str) -> Path:
    try:
        from .registries.cli_registry import default_registry
        return global_template_path(default_registry().get(name))
    except (ImportError, KeyError):
        return DATA_DIR / _FALLBACKS[name]['template']


CLAUDE_HOME        = _backend_home('claude')
OPENCODE_HOME      = _backend_home('opencode')
GITHUB_HOME        = _backend_home('copilot')
DIST_CLAUDE_DIR    = _backend_dist('claude')
DIST_OPENCODE_DIR  = _backend_dist('opencode')
DIST_GITHUB_DIR    = _backend_dist('copilot')
GLOBAL_CLAUDE_MD   = _backend_template('claude')
GLOBAL_OPENCODE_MD = _backend_template('opencode')
GLOBAL_COPILOT_MD  = _backend_template('copilot')
