#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

mkdir -p .opencode-plugin

# Generate index.js from template by substituting placeholders.
python3 - <<'PYEOF'
import pathlib
import re

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        import subprocess, sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "tomli", "--quiet"])
        import tomli as tomllib

raw = pathlib.Path("pyproject.toml").read_bytes()
cfg = tomllib.loads(raw.decode())
proj = cfg["project"]

name = proj["name"]
description = proj["description"]
version = pathlib.Path("agent_notes/VERSION").read_text().strip()

# Resolve vault path from agent-notes memory config.
# Fall back to "disabled" if the module is not installed or config not set.
vault_path = "disabled"
try:
    from agent_notes.services import memory_backend as _mb
    import agent_notes.install_state as _state
    backend = getattr(_state, "memory_backend", None)
    custom = getattr(_state, "memory_custom_path", "")
    if backend and backend != "none":
        from agent_notes.config import memory_dir_for_backend
        p = memory_dir_for_backend(backend, custom)
        if p:
            vault_path = str(p)
except Exception:
    pass

header = "Auto-generated by scripts/build-opencode-plugin.sh — do not hand-edit"

template = pathlib.Path("agent_notes/data/plugin/opencode-index.js.template").read_text()

output = template
output = output.replace("{{HEADER}}", header)
output = output.replace("{{VERSION}}", version)
output = output.replace("{{DESCRIPTION}}", description)
output = output.replace("{{VAULT_PATH}}", vault_path)

pathlib.Path(".opencode-plugin/index.js").write_text(output)
print(f"OpenCode plugin generated: {name} v{version}, vault={vault_path}")
PYEOF

# Generate package.json so Bun's npm-style loader can find the plugin.
python3 - <<'PYEOF'
import json, pathlib

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        import subprocess, sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "tomli", "--quiet"])
        import tomli as tomllib

raw = pathlib.Path("pyproject.toml").read_bytes()
cfg = tomllib.loads(raw.decode())
proj = cfg["project"]

version = pathlib.Path("agent_notes/VERSION").read_text().strip()
urls = proj.get("urls", {})
repository = urls.get("Repository", urls.get("Homepage", ""))

pkg = {
    "_generated": "Auto-generated by scripts/build-opencode-plugin.sh — do not hand-edit",
    "name": proj["name"] + "-opencode-plugin",
    "version": version,
    "description": proj["description"],
    "main": "./index.js",
    "type": "module",
    "repository": repository,
}

pathlib.Path(".opencode-plugin/package.json").write_text(json.dumps(pkg, indent=2) + "\n")
print("OpenCode package.json generated.")
PYEOF
