#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
python3 -m agent_notes.commands.build
rm -rf .claude-plugin/agents
mkdir -p .claude-plugin/agents
for f in agent_notes/dist/claude/agents/*.md; do
  name=$(basename "$f")
  if [ "$name" != "lead.md" ]; then
    cp "$f" ".claude-plugin/agents/$name"
  fi
done
echo "Plugin agents rebuilt."

# Sync vendored skills from the explicit allow-list in data/plugin/claude.yaml.
# Only skills listed there are included; add to that file to vendor a new skill.
python3 - <<'PYEOF'
import yaml, pathlib, shutil

config = yaml.safe_load(pathlib.Path("agent_notes/data/plugin/claude.yaml").read_text())
vendored = config.get("vendored_skills", [])
skills_dst = pathlib.Path(".claude-plugin/skills")

for skill in vendored:
    src = pathlib.Path(f"agent_notes/dist/skills/{skill}/SKILL.md")
    dst_dir = skills_dst / skill
    dst_dir.mkdir(parents=True, exist_ok=True)
    if src.exists():
        shutil.copy(src, dst_dir / "SKILL.md")
    else:
        print(f"  Warning: skill source not found: {src}")

print(f"Plugin skills synced ({len(vendored)} vendored).")
PYEOF

# Generate plugin.json fully from pyproject.toml + VERSION + claude.yaml.
# This file is auto-generated — hand-edits will be overwritten on next build.
python3 - <<'PYEOF'
import json, pathlib

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        import subprocess, sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "tomli", "--quiet"])
        import tomli as tomllib

import yaml

raw = pathlib.Path("pyproject.toml").read_bytes()
cfg = tomllib.loads(raw.decode())
proj = cfg["project"]

version = pathlib.Path("agent_notes/VERSION").read_text().strip()

plugin_cfg = yaml.safe_load(pathlib.Path("agent_notes/data/plugin/claude.yaml").read_text())
vendored = plugin_cfg.get("vendored_skills", [])

authors = proj.get("authors", [])
author_name = authors[0]["name"] if authors else ""

urls = proj.get("urls", cfg.get("project", {}).get("urls", {}))
repository = urls.get("Repository", urls.get("Homepage", ""))

manifest = {
    "_generated": "Auto-generated by scripts/build-claude-plugin.sh — do not hand-edit",
    "name": proj["name"],
    "version": version,
    "description": proj["description"],
    "author": {"name": author_name},
    "repository": repository,
    "license": proj.get("license", ""),
    "keywords": proj.get("keywords", []),
    "agents": "./.claude-plugin/agents/",
    "skills": "./.claude-plugin/skills/",
    "hooks": {
        "SessionStart": [
            {
                "matcher": "",
                "hooks": [
                    {
                        "type": "command",
                        "command": "cat ~/.claude/agent-notes-context.md 2>/dev/null || true"
                    }
                ]
            }
        ]
    }
}

pathlib.Path(".claude-plugin/plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(f"Plugin manifest generated: {proj['name']} v{version} ({len(vendored)} skills vendored).")
PYEOF
